### ISSUE TITLE
Feature Request: Interactive Buttons

### ISSUE THREAD

**Issue by ehaselwanter** [litaio/lita-slack#97] opened 2016-06-22 14:35 UTC
How do you think about supporting https://api.slack.com/docs/message-buttons

**Comment by jimmycuadra** [comment] 2016-06-22 22:44
Dupe of litaio/lita#192. Also see discussion in #93 for why there won't be any more Slack-specific features supported at the adapter level.

**Closed by jimmycuadra** 2016-06-22 22:44 UTC

**Comment by ehaselwanter** [comment] 2016-06-23 07:26
understood. any thoughts about how to share common code, so that plugin authors can opt-in?

**Comment by jimmycuadra** [comment] 2016-06-23 08:12
I guess it depends on what needs to be shared. In some cases all that's needed is a simple API call to Slack, which only involves a client library. I'm not sure what the use cases are that would require a deeper integration with Lita, but we can address them and find a good approach as they come up. One possible way is a Lita extension plugin. That might not even be necessary, but we'll see.
